# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8125858ddd2d6e36c745a342247554a622412868efb0886b9b62adef2c0148f16f93af1f60cc13673d343813e89c981c746a36baa4599b83430a33aa8f948265

test:
  secret_key_base: 950f8ed5cefb459280d473165e82695355901d05b18d8ba1d141b71b79df8405df4cbde6eec24c29b9193147b3e5c3d3dfab0e925b58b0fdd1f64dc2a39952a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
